version: "3.9"
services:
  hardhat:
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/home/hardhat/.config/gh:ro
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
  vscode-extensions-insiders:
