name: Mythril

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-slither-analysis:
    name: Run Mythril analysis
    runs-on: ubuntu-latest
    container:
      image: utkusarioglu/ethereum-dev-environment:latest
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        ALCHEMY_ETHEREUM_KOVAN_API_KEY:
          ${{ secrets.ALCHEMY_ETHEREUM_KOVAN_API_KEY }}
        ALCHEMY_POLYGON_MUMBAI_API_KEY:
          ${{ secrets.ALCHEMY_POLYGON_MUMBAI_API_KEY }}
        GOERLI_DEPLOYER_PK: ${{ secrets.GOERLI_DEPLOYER_PK }}
        LOCAL_DEPLOYER_PK: ${{ secrets.LOCAL_DEPLOYER_PK }}
        LOCAL_USER_1_PK: ${{ secrets.LOCAL_USER_1_PK }}
        LOCAL_USER_2_PK: ${{ secrets.LOCAL_USER_2_PK }}
        LOCAL_USER_3_PK: ${{ secrets.LOCAL_USER_3_PK }}
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn --frozen-lockfile --no-progress --production false
      - name: Compile contracts
        shell: bash
        run: yarn hardhat compile
      - name: Install solc for crytic-compile
        shell: bash
        run: scripts/solc-select-install.sh
      - name: Mythril analysis
        shell: bash
        run: scripts/mythril-analyze.sh
