name: Slither

on:
  workflow_dispatch:

jobs:
  run-slither-analysis:
    name: Run Slither analysis
    runs-on: ubuntu-latest
    container:
      image: utkusarioglu/ethereum-dev-environment
      options: --user root
      env:
        ALCHEMY_POLYGON_MUMBAI_API_KEY:
          ${{ secrets.ALCHEMY_POLYGON_MUMBAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn --frozen-lockfile --no-progress --production false
      - name: Slither analysis
        shell: bash
        run: |
          slither .
