name: Slither

on:
  workflow_dispatch:

jobs:
  run-slither-analysis:
    name: Run Slither analysis
    runs-on: ubuntu-latest
    container:
      image: utkusarioglu/ethereum-dev-environment
      options: --user 0
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        ALCHEMY_ETHEREUM_KOVAN_API_KEY:
          ${{ secrets.ALCHEMY_ETHEREUM_KOVAN_API_KEY }}
        ALCHEMY_POLYGON_MUMBAI_API_KEY:
          ${{ secrets.ALCHEMY_POLYGON_MUMBAI_API_KEY }}
        GOERLI_DEPLOYER_PK: ${{ secrets.GOERLI_DEPLOYER_PK }}
        LOCAL_DEPLOYER_PK: ${{ secrets.LOCAL_DEPLOYER_PK }}
        LOCAL_USER_1_PK: ${{ secrets.LOCAL_USER_1_PK }}
        LOCAL_USER_2_PK: ${{ secrets.LOCAL_USER_2_PK }}
        LOCAL_USER_3_PK: ${{ secrets.LOCAL_USER_3_PK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn --frozen-lockfile --no-progress --production false
      - name: Slither analysis
        shell: bash
        run: |
          slither .
